In [1]:
import pandas as pd

In [20]:
metadata = pd.read_csv('/Users/polzovatel/Downloads/SraRunTable-2.csv')
down = pd.read_csv('/Users/polzovatel/Downloads/srr_list.csv', header=None)

In [40]:
metadata

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,SRA Study,host_body_mass_index,host_diet,host_phenotype,misc_param,host_occupation,cross_sectional_multiomics_cohort,host_bowel_habit,host_education,Repeats
0,SRR22709634,RNA-Seq,280,1480810784,PRJNA812699,SAMN27387095,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",478921435,UCLA,not collected,...,SRP367319,27.799999,Standard_American,NaN,NaN,NaN,NaN,Constipation,NaN,NaN
1,SRR22709635,RNA-Seq,279,1329858096,PRJNA812699,SAMN27387307,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",436761773,UCLA,not collected,...,SRP367319,31.225857,Modified_American,NaN,NaN,NaN,NaN,Constipation,Some_college,NaN
2,SRR22709636,RNA-Seq,278,1254299119,PRJNA812699,SAMN27387246,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",428599501,UCLA,not collected,...,SRP367319,18.802130,Modified_American,NaN,NaN,NaN,NaN,Normal,High_school_grad,NaN
3,SRR22709637,RNA-Seq,279,1250496800,PRJNA812699,SAMN27387256,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",432198343,UCLA,not collected,...,SRP367319,23.772947,Standard_American,NaN,NaN,NaN,NaN,Diarrhea,Any_postgraduate_education,NaN
4,SRR22709638,RNA-Seq,274,1078576270,PRJNA812699,SAMN27387205,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",365808788,UCLA,not collected,...,SRP367319,25.014921,Modified_American,NaN,NaN,NaN,NaN,Mixed,Some_college,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,SRR22709956,RNA-Seq,278,1170282829,PRJNA812699,SAMN27387295,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",401851632,UCLA,not collected,...,SRP367319,20.767914,Vegetarian,NaN,NaN,NaN,NaN,Diarrhea,Some_college,NaN
323,SRR22709957,RNA-Seq,276,1091555182,PRJNA812699,SAMN27387137,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",353987034,UCLA,not collected,...,SRP367319,22.119177,Pescetarian,NaN,NaN,NaN,NaN,Diarrhea,Some_college,NaN
324,SRR22709958,RNA-Seq,272,1367804095,PRJNA812699,SAMN27387262,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",455057193,UCLA,not collected,...,SRP367319,27.565926,Standard_American,NaN,NaN,NaN,NaN,Normal,College_grad,NaN
325,SRR22709959,RNA-Seq,274,1593789339,PRJNA812699,SAMN27387316,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",519027566,UCLA,not collected,...,SRP367319,21.110596,Vegetarian,NaN,NaN,NaN,NaN,Normal,Some_college,NaN
326,SRR22709960,RNA-Seq,267,1166894217,PRJNA812699,SAMN27387203,"MIMS.me,MIGS/MIMS/MIMARKS.human-gut",377308054,UCLA,not collected,...,SRP367319,29.265825,Lactose_free,NaN,NaN,NaN,NaN,Normal,High_school_grad,NaN

In [41]:
down = down.drop_duplicates()

In [51]:
df_new = metadata[~metadata['Run'].isin(down[0])]

In [57]:
america = df_new[df_new['host_diet'] == 'Modified_American']

In [80]:
ibs_new = america[america['gastrointest_disord'] == 'IBS']
control_new = america[america['gastrointest_disord'] == 'Control']

In [81]:
ibs_new = ibs_new.iloc[0:20, :]
control_new = control_new.iloc[0:20, :]
ibs_new.to_csv('/Users/polzovatel/Downloads/ibs_new.csv', header=True)
control_new.to_csv('/Users/polzovatel/Downloads/control_new.csv', header=True)

In [82]:
[print(i) for i in ibs_new['Run']]

SRR22709644
SRR22709647
SRR22709651
SRR22709655
SRR22709656
SRR22709659
SRR22709660
SRR22709661
SRR22709666
SRR22709674
SRR22709677
SRR22709694
SRR22709706
SRR22709709
SRR22709727
SRR22709728
SRR22709742
SRR22709745
SRR22709752
SRR22709760

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [84]:
[print(i) for i in control_new['Run']]

SRR22709640
SRR22709658
SRR22709664
SRR22709685
SRR22709690
SRR22709693
SRR22709697
SRR22709715
SRR22709723
SRR22709747
SRR22709753
SRR22709757
SRR22709765
SRR22709776
SRR22709778
SRR22709789
SRR22709791
SRR22709794
SRR22709796
SRR22709804

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [ ]:
df.groupby(['sample', 'gene']).agg({'read_id': 'nunique'}) 
df.groupby(['sample', 'col_2']).agg({'read_id': 'count'})

In [129]:
diamond_control = pd.read_csv('/Users/polzovatel/Downloads/hackaton/diamond_control.tsv', header=None, sep='\t')

In [130]:
diamond_control

,0,1,2,3,4,5,6,7,8,9,10,11
0,SRR22709636.14532,AYG21321.1,43.6,39,22,0,2,118,45,83,1.590000e-05,30.4
1,SRR22709636.74278,EJF39103.1,58.8,34,14,0,2,103,171,204,8.230000e-10,42.0
2,SRR22709636.213392,ADE70661.1,47.2,36,19,0,25,132,1,36,3.650000e-08,37.7
3,SRR22709636.288057,ADE70661.1,50.0,36,18,0,7,114,1,36,2.170000e-09,41.2
4,SRR22709636.290852,EJF39099.1,44.9,49,27,0,1,147,100,148,7.390000e-11,45.4
...,...,...,...,...,...,...,...,...,...,...,...,...
9366,SRR22709916.4104365,EJF39099.1,50.0,48,24,0,144,1,154,201,8.860000e-14,53.5
9367,SRR22709916.4152373,PRO65849.1,51.2,43,21,0,143,15,149,191,7.260000e-13,50.8
9368,SRR22709916.4153175,PRO65849.1,51.2,43,21,0,143,15,149,191,7.260000e-13,50.8
9369,SRR22709916.4235053,EJF39103.1,46.4,28,15,0,85,2,83,110,8.200000e-08,35.8
9370,SRR22709916.4242985,PRO65849.1,52.4,42,20,0,141,16,149,190,7.260000e-13,50.8

In [131]:
diamond_control = diamond_control[(diamond_control[10] < 1e-03) & (diamond_control[11] > 40)]

In [132]:
diamond_control

,0,1,2,3,4,5,6,7,8,9,10,11
1,SRR22709636.74278,EJF39103.1,58.8,34,14,0,2,103,171,204,8.230000e-10,42.0
3,SRR22709636.288057,ADE70661.1,50.0,36,18,0,7,114,1,36,2.170000e-09,41.2
4,SRR22709636.290852,EJF39099.1,44.9,49,27,0,1,147,100,148,7.390000e-11,45.4
8,SRR22709636.507181,PRO65852.1,57.8,45,17,1,19,147,99,143,2.420000e-12,49.7
9,SRR22709636.524493,ADE70661.1,52.8,36,17,0,28,135,1,36,6.030000e-10,42.7
...,...,...,...,...,...,...,...,...,...,...,...,...
9365,SRR22709916.4080263,A0A3A6N9T6.1,56.3,48,21,0,145,2,183,230,1.520000e-11,47.4
9366,SRR22709916.4104365,EJF39099.1,50.0,48,24,0,144,1,154,201,8.860000e-14,53.5
9367,SRR22709916.4152373,PRO65849.1,51.2,43,21,0,143,15,149,191,7.260000e-13,50.8
9368,SRR22709916.4153175,PRO65849.1,51.2,43,21,0,143,15,149,191,7.260000e-13,50.8
9370,SRR22709916.4242985,PRO65849.1,52.4,42,20,0,141,16,149,190,7.260000e-13,50.8

In [133]:
sample_id = []
for i in diamond_control[0]:
    sample_id.append(i.split('.')[0])

In [134]:
diamond_control[12] = sample_id

/var/folders/6b/srtlxlxn0pz5b_ks7sdgt7lm0000gn/T/ipykernel_13380/1081679138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamond_control[12] = sample_id

In [139]:
diamond_control.columns = diamond_control.columns.astype(str)

diamond_control.groupby(['12', '1']).agg({'0': 'nunique'}).sort_values('0', ascending=False).value_counts('1')

1
A0A3A6N9T6.1      19
EJF39099.1        19
WP_017967307.1    19
PRO65853.1        19
EJF39090.1        19
PRO65852.1        18
WP_017967310.1    18
EJF39089.1        17
EJF39103.1        17
ADE70661.1        17
PRO65849.1        15
PRO65854.1        12
AYG21324.1        11
AYG21321.1         9
AYG21326.1         8
AAK90112.1         3
AYG21322.1         1
AYG21325.1         1
A0A3A6NE59.1       1
MCD5344479.1       1
Name: count, dtype: int64

Low counts per gene....